language: python
python:
  - 2.6
# command to install dependencies
# UPDATE THIS FILE IF RENPY VERSION IS UPDATED
install:
  - cd ..
  - wget http://www.renpy.org/dl/7.0.0/renpy-7.0.0-sdk.tar.bz2
  - tar xf renpy-7.0.0-sdk.tar.bz2
  - rm renpy-7.0.0-sdk.tar.bz2
  - mv renpy-7.0.0-sdk renpy
  - cd renpy
# command to run tests
script: ./renpy.sh "../demo/" lint && ./renpy.sh launcher distribute "../demos/"